### ISSUE TITLE
Refactor AB-3 to StudyTracker

### ISSUE THREAD

**Issue by joenzkimchan** [AY2122S1-CS2103T-T09-1/tp#11]
The AB-3 code base has not been refactored for our idea, StudyTracker.

Lets refactor the code, so that the variable/method/class names make sense.

**Comment by qreoct** [comment]
I've made more additions in #22, most of the logical part of the code (e.g. class names, variables, comments) have been refactored.

**Parts of the code that still need work**:
- FXML files and css class names
- Commands need to be tweaked to match our specified format (in UG and DG)
- Json files need to have default data changed
- Removal of no-longer needed fields (e.g. phone number), and adding StudyTracker-specific fields (e.g. Amenity, Rating). [This tutorial could be helpful](https://nus-cs2103-ay2122s1.github.io/tp/tutorials/RemovingFields.html)
