### ISSUE TITLE
[PE-D] User Guide should specify somewhere on what are the valid inputs for 'Amenities'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-1/tp#176]
Some place in the User Guide should specify what the valid inputs for 'Amenities' are. The error message in the app should also state that it is case-sensitive.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: nhjryan/ped#8

**Comment by ruoyann** [comment]
We can make the amenities non-case sensitive
