### ISSUE TITLE
[PE-D] Cannot `unfav` a study spot

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-1/tp#180]
Steps:
- Add new spot MyRoom
- Add this spot to fav
- unfav this spot

The study spot shows up in the fav list, but it cannot be `unfav`ed.

![Screenshot 2021-10-29 at 4.48.59 PM.png](https://raw.githubusercontent.com/uyencfi/ped/master/files/319096b0-850f-4fb1-b9fd-a1b108978632.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: uyencfi/ped#2

**Comment by mslevis** [comment]
Cannot be replicated using the steps given in the bug report. Could be linked to #185 where tester deleted `MyRoom` and tried to unfavourite it after.
