### ISSUE TITLE
[PE-D] 'log -r' takes in both 'n/' and 'hr/' parameters but works as intended

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-1/tp#186]
Small issue, but maybe it should warn me if I try to put in both 'n/' and 'hr/' for reset.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nhjryan/ped#10

**Comment by mslevis** [comment]
This is expected behaviour as `log -r` does not expect other parameters and will ignore them. Great suggestion though it may be out of the scope of v1.4.
