### ISSUE TITLE
[PE-D] Outdated image in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-1/tp#190]
The image seems to be from an earlier version of the app.

![image.png](https://raw.githubusercontent.com/uyencfi/ped/master/files/255c6a75-a7f9-42a5-8054-480731efc775.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: uyencfi/ped#4

**Comment by joenzkimchan** [comment]
Same as #205
