### ISSUE TITLE
[PE-D] Suggestion: It would be nice to use index reference for some commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-1/tp#210]
I saw that one of your Non-Functional Requirements in the developer guide was that using CLI should be faster than using a mouse.

However, it can be slow and troublesome to type out long names of study spots. Especially when all characters have to match.

Perhaps allowing the user to use the index beside the study spots would be faster.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: KelvinSoo/ped#9

**Comment by joenzkimchan** [comment]
Great suggestion, but due to limitations of 1.4, we cannot add this feature
