### ISSUE TITLE
Add Favourites to StudySpot

### ISSUE THREAD

**Issue by mslevis** [AY2122S1-CS2103T-T09-1/tp#31]

**Comment by qreoct** [comment]
**Concept:** a FavouriteCommand that allows us to save certain locations into a list of favourites.

Possible syntax: `fav n/Bishan Library`

Result: `Added 'Bishan Library' to favourites!`

We should be able to remove locations from favourites as well.

Listing all locations should show showing if a particular location is in Favourites.

Example (using the heart Unicode character, `♥`, to show that Bishan Library is in favourites):
```
list
```
```
1. Bishan Library (♥) ★★★★★ [aircon][wifi] 
#not-crowded

2. SRC Utown ★★★★★ [aircon][wifi]
#crowded
```

**Implementation:**
- Should we limit the number of favourites that a user can have? E.g. a User can at most have 5 favourited locations.
- Should we have a `fav` and `unfav` command? Or should `fav` toggle the favourite status of a location?

**Potential future enhancements:**
- Filter by favourites (#45)
- To show the list of favourites in the GUI, similar to the ObservableList and how it changes when filters are applied.
