### ISSUE TITLE
Refactor Tests

### ISSUE THREAD

**Issue by mslevis** [AY2122S1-CS2103T-T09-1/tp#40]

**Comment by qreoct** [comment]
- [ ] Clean up old tests left over from AB3 to meet new functionality
- [ ] Write tests for Amenities
- [ ] Write tests for Ratings
- [ ] Write tests for changed Edit Command
- [ ] Clean up default JSON files and test stubs left over from AB3

**Comment by qreoct** [comment]
With #51 merged, this is done!
